#define MAX_OBJ_VERTICES 1000
#define MAX_OBJ_FACES 1000

#define MAP_SCALE 0.4
#define MAP_TRANSLATE_FACTOR 2*MAP_SCALE

#define MAP_SIZE 20
#define MAP_WORKERS 10
#define MAP_WORKTIME 50

#define PLAYER_ID 0

#define DEADZONE 25
